### ISSUE TITLE
Possible to assign NaN to a NotNan value using sqrt(-1)

### ISSUE THREAD

**Issue by Ameliorate** [olson-sean-k/decorum#11]
```rust
use decorum::{N64, Real};

fn main() {
    let nan = N64::from(-1.0).sqrt();

    assert!(nan.into_inner().is_nan());
    println!("nan: {}", nan);
}
```

The above code runs and prints `nan: NaN`. It is expected to panic instead.

You should also check https://en.wikipedia.org/wiki/NaN#Operations_generating_NaN to make sure there aren't any more operations that can be exploited to produce NaN.

**Comment by olson-sean-k** [comment]
Thanks for reporting this! This should be fixed by 9ac0380. That commit changes the implementation of `Real` to use checked conversions for most operations, because they can yield values that are potentially disallowed like `NaN` and `INF`.

Testing could certainly be improved, though this failed due to an explicit unchecked conversion used in `sqrt`. `NaN`s are detected via `is_nan`, which should cover the cases listed in the linked article.
