### ISSUE TITLE
Point of the std feature

### ISSUE THREAD

**Issue by jplatte** [olson-sean-k/decorum#14]
I've had a look at the code and I don't see the `std` feature being used anywhere. Why is there a `std` feature and a conditional `extern crate std;` declaration if that is never used anywhere?

Note that removing these will still result in the default features being no_std-incompatible, due to serde(-derive)'s default features being enabled. You probably don't depend on serde's std feature though (at least I don't see how you would). If your crate indeed works with `serde = { version = "1.0", default-features = false }`, your crate could unconditionally be no_std compatible. It would be a breaking change for anyone manually specifying features though.

**Comment by olson-sean-k** [comment]
Thanks for opening this! I actually just had a look at this recently and the `std` feature is definitely broken. At the time, I wasn't too familiar with what was involved to rely on `core` instead of `std`, and 59354fe missed some very important changes that are required. A non-exhaustive list of issues when the `std` feature is **disabled**:

- Traits like `Float` from `num-traits` are still used, despite them requiring `std`.
- Dependencies are not properly configured, including `serde` (as you pointed out).
- The `Real` trait is enabled as-is, which is likely not possible in non-`std` environments.

I already have some changes on the way to address these, but I'm not sure yet when they'll be ready. I'll be sure to update this issue though. It will be a breaking change and I'll probably bump the version and publish once the changes land.

**Comment by olson-sean-k** [comment]
This should be fixed by 4fa3732. That change uses conditional compilation to remove mathematical operations from the `Real` trait, omit `Float` and `Real` from `num-traits`, and properly configure dependencies on `serde` in `#[no_std]` environments. I'm still planning some followup changes to help test this in the future.

Sorry for the delay on this.

**Comment by jplatte** [comment]
> Sorry for the delay on this.

You had no obligation to work on this. Also, this came up when evaluation whether to use this crate and I can't even remember what for exactly, so I wasn't even waiting for a fix :sweat_smile:
