### ISSUE TITLE
Is there a way to create custom constraints?

### ISSUE THREAD

**Issue by NeverGivinUp** [olson-sean-k/decorum#15]
I'd like to define custom constraints on floating points, like 
* positive real
* unit-range (between 0.0 and 1.0)

Is that possible already? If so, am I missing the documentation?

**Comment by olson-sean-k** [comment]
Decorum does not support custom constraints. The constraint mechanism is an implementation detail. `ConstrainedFloat` is exported for documentation purposes, since it would otherwise be difficult to determine which traits type aliases like `NotNan` implement.

I had considered expanding the scope of Decorum in #6, but decided against that. The constraints provided are specific to the encoding and implementation of IEEE-754 floating-point values (`INF` and `NaN`). I think constraints like a unit-range would be better done separately. I mention similar constraints in #6.

(Sorry for the delayed response; I'm traveling right now and have very limited Internet access.)

**Comment by olson-sean-k** [comment]
I'm closing this issue, but feel free to discuss or reopen.
