### ISSUE TITLE
R64 does not satisfy nalgebra::Real

### ISSUE THREAD

**Issue by alxarch** [olson-sean-k/decorum#18]
I get the following error while tryring to use `magnitude()` on a `nalgebra::Vector3<decorum::R64>`:

```
no method named `magnitude` found for type `na::Matrix<decorum::ConstrainedFloat<f64, decorum::constraint::FiniteConstraint<f64>>, na::U3, na::U1, na::ArrayStorage<decorum::ConstrainedFloat<f64, decorum::constraint::FiniteConstraint<f64>>, na::U3, na::U1>>` in the current scope

note: the method `magnitude` exists but the following trait bounds were not satisfied:
      `decorum::ConstrainedFloat<f64, decorum::constraint::FiniteConstraint<f64>> : na::Real`rustc(E0599)
```
The same problem comes up with `normalize()` but I can bypass using `plexus::geomertry::ops::Normalize` trait. Is this how it's supposed to be? Should I bypass the magnitude issue by implementing my own trait?

(I'm new to Rust, sorry if I'm missing something obvious here)

**Comment by olson-sean-k** [comment]
Decorum's types do not implement `nalgebra`'s `RealField` trait, which is required for the `magnitude` and `normalize` APIs. This problem is being discussed in #16 and there's [an issue opened against `alga`](https://github.com/rustsim/alga/issues/83) as well.

I'm hoping that the requirements for `RealField` and `ComplexField` may be relaxed. Depending on that discussion, I may implement `RealField` behind a Cargo feature.

If you're using Plexus, I recommend using a recent commit from `master`, as the last release on crates.io is quite stale. Plexus now abstracts Euclidean spaces using the [Theon crate](https://github.com/olson-sean-k/theon), which provides APIs that include Euclidean norms and should support `R64`.

**Comment by alxarch** [comment]
Will try that, thanks!
