### ISSUE TITLE
Improve `Debug` implementation

### ISSUE THREAD

**Issue by athre0z** [olson-sean-k/decorum#19]
Hello there and thank you for the lib!

Currently, `std::fmt::Debug` is implemented for the float types via a derive. However, due to it containing a `PhantomData` field, the output is rather chunky. It looks like like:

```rust
ConstrainedFloat {
    value: -0.00025,
    phantom: PhantomData,
}
```

With structs that have a lot of floating point members, this printing is very noisy. Personally, I'd prefer if we could perhaps instead just print the floating point literal?

Please let me know what you think -- If you're ok with this, I'd be happy to PR this!

**Comment by olson-sean-k** [comment]
Thanks for opening this! I totally agree: the `Debug` implementation is very noisy and a custom implementation would be better.

The `Display` implementation provides transparent formatting, and I think that `Debug` should probably differentiate proxy types from primitive types. Perhaps it could print `ConstraintedFloat(-0.00025)` so that it's clear that values are not simply primitive types like `f32` or `f64`. If that's still too verbose, I'm happy to discuss alternatives.

If you're willing to put together a PR, that'd be great. :+1:
